workspace = { members = ["grid"] }
[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.2"
grid = { version = "*", path = "grid" }
paste = "1.0.15"
clap = { version = "4.5.4", features = ["derive"] }
cached = "0.51.3"
num-integer = "0.1.46"
